package com.fekete.cvlibg.metrics

import com.fekete.cvlibg.utils.TimerResult

/**
 * Metrics generated by the image analysis process
 *
 * @param totalTime total time from receiving image data to emitting data.
 * @param detectorPerformanceMetrics map of [TimerResult] values from the [com.fekete.cvlibg.detection.Detector].
 * Classes derived from [com.fekete.cvlibg.detection.AbstractYoloDetector] should use string keys stored in its
 * companion object.
 * @param detectorMetrics list of other metrics provided by the detector
 *
 * @author Denis Fekete, (xfeket01@vutbr.cz), (denis.fekete02@gmail.com)
 */
data class AnalyzerMetrics(
    val totalTime: TimerResult,
    val detectorPerformanceMetrics: Map<String, TimerResult>,
    val detectorMetrics: List<MetricsValue>

)
